REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA consolidation FROM consolidation_app;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA consolidation FROM consolidation_app;
REVOKE USAGE ON SCHEMA consolidation FROM consolidation_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA consolidation REVOKE ALL PRIVILEGES ON SEQUENCES FROM consolidation_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA consolidation REVOKE ALL PRIVILEGES ON TABLES FROM consolidation_app;
DROP ROLE IF EXISTS consolidation_app;
