DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'ledger_app') THEN
        CREATE ROLE ledger_app WITH LOGIN PASSWORD 'ledger_secret';
    END IF;
END
$$;

GRANT USAGE ON SCHEMA ledger TO ledger_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ledger TO ledger_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ledger TO ledger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ledger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger GRANT USAGE, SELECT ON SEQUENCES TO ledger_app;
