REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA ledger FROM ledger_app;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA ledger FROM ledger_app;
REVOKE USAGE ON SCHEMA ledger FROM ledger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger REVOKE ALL PRIVILEGES ON SEQUENCES FROM ledger_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA ledger REVOKE ALL PRIVILEGES ON TABLES FROM ledger_app;
DROP ROLE IF EXISTS ledger_app;
